# [*]
# ctx-size = 32768
# n-gpu-layers = 99


[Qwen3.6-35B-A3B-Uncensored-Aggressive-Q4_K_M]
model = /home/baka/.models/HauhauCS/Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive/Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive-Q4_K_M.gguf
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
presence-penalty = 0
cache-type-k = q8_0
cache-type-v = q8_0
flash-attn = on
jinja = true
chat-template-file = /home/baka/.models/templates/chat_template.jinja
ctx-size = 131072
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 32768
tags = HauhauCS


[GLM4.7-Flash-30B-A3B-UD-Q4_K_XL]
model = /home/baka/.models/GLM/GLM-4.7-Flash-UD-Q4_K_XL.gguf
temp = 1.0
top-p = 0.95
min-p = 0.01
repeat-penalty = 1.0
presence-penalty = 0
cache-type-k = q8_0
cache-type-v = q8_0
flash-attn = on
jinja = true
ctx-size = 131072
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 32768
tags = Unsloth

# llama serve -m GLM-4.7-Flash-UD-Q4_K_XL.gguf --temp 1.0 --top-p 0.95 --repeat-penalty 1.0 --min-p 0.01 -c 100000


# Thinking mode (default):
# General: temperature=1.0, top_p=0.95, top_k=20, min_p=0, presence_penalty=1.5
# Coding/precise tasks: temperature=0.6, top_p=0.95, top_k=20, min_p=0, presence_penalty=0
#
# Non-thinking mode:
# General: temperature=0.7, top_p=0.8, top_k=20, min_p=0, presence_penalty=1.5
# Reasoning tasks: temperature=1.0, top_p=1.0, top_k=40, min_p=0, presence_penalty=2.0

# [Qwen3.5-9B-Uncensored-Aggressive-Q6_K]
# model = /home/baka/.models/HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive-Q6_K/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive-Q6_K.gguf
# ngl = 99
# flash-attn = on
# np = 1
# temp = 0.6
# top-p = 0.95
# top-k = 20
# min-p = 0.00
# presence-penalty = 0
# cache-type-k = q8_0
# cache-type-v = q8_0
# jinja = true
# chat-template-file = /home/baka/.models/templates/chat_template.jinja
# ctx-size = 131072
# rope-scaling = yarn
# rope-scale = 4
# yarn-orig-ctx = 32768
# tags = HauhauCS


# [Gemma4-26B-A4B-Uncensored-Balanced-Q4_K_M]
# model = /home/baka/.models/HauhauCS/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced/Gemma4-26B-A4B-Uncensored-HauhauCS-Balanced-Q4_K_M.gguf
# ctx-size = 100000
# temp = 1
# top-k = 64
# top-p = 0.95
# flash-attn = on
# parallel = 1
# tags = HauhauCS


[Qwopus3.5-9B-Coder-MTP-Q5_K_M]
model =  /home/baka/.models/Qwopus/Qwopus3.5-9B-Coder-MTP-Q5_K_M/Qwopus3.5-9B-Coder-MTP-Q5_K_M.gguf
ngl = 99
fa = on
np = 1
spec-type = draft-mtp
spec-draft-n-max = 2
jinja = true
chat-template-file = /home/baka/.models/templates/chat_template.jinja
cache-type-k = q8_0
cache-type-v = q8_0
ctx-size = 131072
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 32768
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
tags = MTP,Coder


[Gemma4-12B-IT-QAT-Q4_K_XL]
model = /home/baka/.models/Unsloth/Gemma4-12B-IT-QAT/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 100000
flash-attn = on
jinja = true
temp = 1.0
top-k = 64
top-p = 0.95
# min-p = 0.05
# repeat-penalty = 1.1
model-draft = /home/baka/.models/Unsloth/Gemma4-12B-IT-QAT/gemma-4-12B-it-Q4_0-MTP.gguf
spec-type = draft-mtp
spec-draft-n-max = 4
parallel = 1
n-gpu-layers = 99
tags = MTP,Unsloth


[Gemma4-26B-A4B-IT-QAT-UD-Q4_K_XL]
model = /home/baka/.models/Unsloth/Gemma4-26B-A4B-it-QAT/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 100000
temp = 1
top-k = 64
top-p = 0.95
flash-attn = on
model-draft = /home/baka/.models/Unsloth/Gemma4-26B-A4B-it-QAT/gemma-4-26b-A4B-it-assistant-Q4_0.gguf
spec-type = draft-mtp
spec-draft-n-max = 4
parallel = 1
tags = MTP,Unsloth


[Qwythos-9B-Claude-Mythos-Uncensored-MTP-Q5_K_M]
model =  /home/baka/.models/Qwythos-9B-Claude-Mythos-5-1M-Q5_K_M-Uncensored/Qwythos-9B-Claude-Mythos-5-1M-MTP-Q5_K_M.gguf
ngl = 99
fa = on
np = 1
jinja = true
chat-template-file = /home/baka/.models/templates/chat_template.jinja
cache-type-k = q8_0
cache-type-v = q8_0
spec-type = draft-mtp
spec-draft-n-max = 2
ctx-size = 131072
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 32768
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.05
tags = Empero-AI
